### ISSUE TITLE
Incorrect location on map: PayPal, 5 Temasek Blvd

### ISSUE THREAD

**Issue by balloontin** [webuildsg/data#50]
In page https://data.webuild.sg/dataset/events-per-location/
One data point's coordinates are incorrect, where the group is "Singapore Ruby Group,Grumpy Gits SG,Agile Singapore" and the address is "PayPal, 5 Temasek Blvd, #09-01 Suntec Tower Five, 038985, Singapore". @sayanee

**Comment by sayanee** [comment]
thank you for spotting it @balloontin :round_pushpin: 🗺 :+1:

**Comment by sayanee** [comment]
This venue shows the default `Singapore` location in the center of Singapore.

![image](https://cloud.githubusercontent.com/assets/413879/13312758/14b11a1a-dbd4-11e5-99c1-04dd90ffd762.png)

**Comment by sayanee** [comment]
[Geocode](https://google-developers.appspot.com/maps/documentation/javascript/examples/full/geocoding-simple) string `5 Temasek Blvd, 038985, Singapore` instead of `5 Temasek Blvd, #09-01 Suntec Tower Five, 038985, Singapore`:

![image](https://cloud.githubusercontent.com/assets/413879/13312864/d6ef812a-dbd4-11e5-85ea-452d758cb557.png)
